services:
  - type: web
    name: inventory-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
